version: '3.1'

services:

  db:
    image: mongodb/mongodb-community-server
    container_name: crs-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME:${DB_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD:${DB_PASSWORD}
    volumes:
      - ${VOLUME_PATH}:/data/db
    ports:
      - 27017:27017
    networks:
      - crs

networks:
  crs:
    external: true
      